version: "3.8"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - movies-app-network

  backend:
    build:
      context: ./movies_DB
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./movies_DB:/movies-app
    container_name: movies-app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      DJANGO_ENVIRONMENT: production # Set to production
    depends_on:
      - db
    networks:
      - movies-app-network

  frontend:
    build:
      context: ./frontend_movies_db
      dockerfile: Dockerfile
    volumes:
      - ./frontend_movies_db:/frontend-dockerized
    container_name: frontend-movies-app
    ports:
      - "3000:3000"
    networks:
      - movies-app-network

volumes:
  db_data:

networks:
  movies-app-network:
    driver: bridge
