version: "3.8"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - movies-app-network

  backend:
    build:
      context: .
      dockerfile: movies_DB/Dockerfile
    container_name: movies-app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      DJANGO_ENVIRONMENT: production
    depends_on:
      - db
    networks:
      - movies-app-network

  frontend:
    build:
      context: .
      dockerfile: frontend_movies_db/Dockerfile
    container_name: frontend-movies-app
    ports:
      - "3000:3000"
    environment:
      #REACT_APP_API_URL: https://movies-db-app-9028b9d60784.herokuapp.com
      REACT_APP_API_URL: http://localhost:8000
    networks:
      - movies-app-network

volumes:
  db_data:

networks:
  movies-app-network:
    driver: bridge
