version: "3.8"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - movies-app-network

  backend:
    build:
      context: .
      dockerfile: movies_DB/Dockerfile
    container_name: movies-app
    ports:
      - "8000:8000"
    environment:
      DJANGO_ENVIRONMENT: production
      DB_NAME: ${DB_NAME}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      HOST: ${HOST}
      PORT: ${PORT}
      SECRET_KEY: ${SECRET_KEY}
      AZURE_ACCOUNT_NAME: ${AZURE_ACCOUNT_NAME}
      AZURE_ACCOUNT_KEY: ${AZURE_ACCOUNT_KEY}
      AZURE_MEDIA_CONTAINER: ${AZURE_MEDIA_CONTAINER}
      AZURE_STATIC_CONTAINER: ${AZURE_STATIC_CONTAINER}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DEBUG: ${DEBUG}
      TMDB_API_KEY: ${TMDB_API_KEY}
    depends_on:
      - db
    networks:
      - movies-app-network

  frontend:
    build:
      context: .
      dockerfile: frontend_movies_db/Dockerfile
    container_name: frontend-movies-app
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: https://movies-db-app-9028b9d60784.herokuapp.com
      #REACT_APP_API_URL: http://localhost:8000
    networks:
      - movies-app-network

volumes:
  db_data:

networks:
  movies-app-network:
    driver: bridge
