name: Deploy The Application to Heroku

on:
  push:
    branches:
      - main # This workflow is triggered on pushes to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # The runner that will execute the workflow

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 # Check out the current repository to the runner

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create .env file
        run: |
          touch .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo PASSWORD=${{ secrets.PASSWORD }} >> .env
          echo DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }} >> .env
          echo USER=${{ secrets.USER }} >> .env
          echo AZURE_ACCOUNT_NAME=${{ secrets.AZURE_ACCOUNT_NAME }} >> .env
          echo AZURE_ACCOUNT_KEY=${{ secrets.AZURE_ACCOUNT_KEY }} >> .env
          echo AZURE_MEDIA_CONTAINER=${{ secrets.AZURE_MEDIA_CONTAINER }} >> .env
          echo AZURE_STATIC_CONTAINER=${{ secrets.AZURE_STATIC_CONTAINER }} >> .env
          echo ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} >> .env
          echo CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }} >> .env
          echo HOST=${{ secrets.HOST }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo DEBUG=False >> .env
          echo TMDB_API_KEY=${{ secrets.TMDB_API_KEY }} >> .env

      - name: Login to Heroku Container Registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} # Log in to Heroku Docker registry

      - name: Build and Push Docker Containers
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker tag movies-db-app_backend registry.heroku.com/movies-db-app/web
          docker push registry.heroku.com/movies-db-app/web
          docker tag movies-db-app_frontend registry.heroku.com/fe-movies-db/web
          docker push registry.heroku.com/fe-movies-db/web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Release Backend Container
        run: heroku container:release web --app movies-db-app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Release Frontend Container
        run: heroku container:release web --app fe-movies-db
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Execute Migrations
        run: heroku run python manage.py migrate --app movies-db-app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Collect Static Files
        run: heroku run python manage.py collectstatic --noinput --app movies-db-app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
