name: Deploy The Application to Heroku

on:
  push:
    branches:
      - main # This workflow is triggered on pushes to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # The runner that will execute the workflow

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 # Check out the current repository to the runner

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Heroku Container Registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} # Log in to Heroku Docker registry

      - name: Build and Push Backend Docker Container
        run: |
          docker-compose -f docker-compose.prod.yml build backend
          docker tag movies-db-app_backend registry.heroku.com/movies-db-app/web
          docker push registry.heroku.com/movies-db-app/web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          DB_NAME: ${{ secrets.DB_NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          USER: ${{ secrets.USER }}
          AZURE_ACCOUNT_NAME: ${{ secrets.AZURE_ACCOUNT_NAME }}
          AZURE_ACCOUNT_KEY: ${{ secrets.AZURE_ACCOUNT_KEY }}
          AZURE_MEDIA_CONTAINER: ${{ secrets.AZURE_MEDIA_CONTAINER }}
          AZURE_STATIC_CONTAINER: ${{ secrets.AZURE_STATIC_CONTAINER }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}

      - name: Build and Push Frontend Docker Container
        run: |
          docker-compose -f docker-compose.prod.yml build frontend
          docker tag movies-db-app_frontend registry.heroku.com/fe-movies-db/web
          docker push registry.heroku.com/fe-movies-db/web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Release Backend Container
        run: heroku container:release web --app movies-db-app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Release Frontend Container
        run: heroku container:release web --app fe-movies-db
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Execute Migrations
        run: heroku run python manage.py migrate --app movies-db-app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Collect static files
        run: heroku run python manage.py collectstatic --noinput --app movies-db-app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
